src/DesportoBundle/Entity/Profissional.php
<?php

namespace DesportoBundle\Entity;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use InvalidArgumentException;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Profissional
 *
 * @ORM\Table(name="profissional")
 * @UniqueEntity(fields={"cpf"}, message="Este CPF já está cadastrado", repositoryMethod="uniqueEntity")
 * @ORM\Entity(repositoryClass="DesportoBundle\Repository\ProfissionalRepository")
 */
class Profissional extends BaseEntity
{
    
    const DIRETOR = "DIRETOR";
    const TECNICO = "TECNICO";
    const JOGADOR = "JOGADOR";
    
    /**
     * @var string
     * @Assert\NotBlank(message="Nome deve ser preenchido")
     * @ORM\Column(type="string", length=50, nullable=false)
     */
    private $nome;
    
    /**
     * @var string
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $foto;
    
    /**
     * @var DateTime
     *
     * @ORM\Column(type="date", nullable=false)
     */
    private $nascimento;
    
    /**
     *  @ORM\Column(type="sexotype", nullable=false)
     */
    private $sexo;

    
    /**
     * @var string
     * @Assert\NotBlank(message="CPF deve ser PReenchido")
     * @ORM\Column(type="string", length=11, nullable=false)
     */
    private $cpf;
    
    /**
     * @var string
     * 
     * @ORM\Column(type="string", length=12, nullable=true)
     */
    private $rg;

    /**
     * @var string
     * 
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    private $endereco;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $telefone;
    
    /**
     * @ORM\ManyToMany(targetEntity="Arquivo", cascade={"all"})
     * @ORM\JoinTable(name="profissional_arquivo",
     *      joinColumns={@ORM\JoinColumn(name="profissional", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="arquivo", referencedColumnName="id", unique=true)}
     * )
     */
    private $arquivos;

    /**
     * @var Collection
     * @ORM\OneToMany(targetEntity="InscricaoProfissional", mappedBy="profissional")
     **/
    private $inscricoes;

    
    /**
     * @var \DateTime
     *
     * @ORM\Column(name="data_exclusao", type="datetime", nullable=true)
     */
    private $dataExclusao;
    
    /**
     * @var Usuario
     *
     * @ORM\ManyToOne(targetEntity="Usuario", inversedBy="profissionaisCadastradas")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="usuario_cadastro", referencedColumnName="id")
     * })
     */
    private $usuarioCadastro;
    
    /**
     * @var Usuario
     *
     * @ORM\ManyToOne(targetEntity="Usuario", inversedBy="profissionaisExcluidas")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="usuario_exclusao", referencedColumnName="id")
     * })
     */
    private $usuarioExclusao;

    
    public function __construct()
    {
        parent::__construct();
        $this->setArquivos(new ArrayCollection());
        $this->setInscricoes(new ArrayCollection());
    }

    public function getNome()
    {
        return $this->nome;
    }

    public function getFoto()
    {
        return $this->foto;
    }

    public function getNascimento()
    {
        return $this->nascimento;
    }

    public function getCpf()
    {
        return $this->cpf;
    }

    public function getRg()
    {
        return $this->rg;
    }

    public function getEndereco()
    {
        return $this->endereco;
    }

    public function getTelefone()
    {
        return $this->telefone;
    }

    public function getArquivos()
    {
        return $this->arquivos;
    }

    public function getDataExclusao()
    {
        return $this->dataExclusao;
    }

    public function setNome($nome)
    {
        $this->nome = $nome;
        return $this;
    }

    public function setFoto($foto)
    {
        $this->foto = $foto;
        return $this;
    }

    public function setNascimento(DateTime $nascimento)
    {
        $this->nascimento = $nascimento;
        return $this;
    }

    public function setCpf($cpf)
    {
        $this->cpf = preg_replace("/[^0-9]/", "", $cpf);
        return $this;
    }

    public function setRg($rg)
    {
        $this->rg = $rg;
        return $this;
    }

    public function setEndereco($endereco)
    {
        $this->endereco = $endereco;
        return $this;
    }

    public function setTelefone($telefone)
    {
        $this->telefone = preg_replace("/[^0-9]/", "", $telefone);
        return $this;
    }

    public function setArquivos(Collection $arquivos)
    {
        $this->arquivos = $arquivos;
        return $this;
    }

    public function setDataExclusao(\DateTime $dataExclusao)
    {
        $this->dataExclusao = $dataExclusao;
        return $this;
    }

    public function getLabel()
    {
        return $this->nome." - ".$this->cpf;
    }


    public function getUsuarioCadastro()
    {
        return $this->usuarioCadastro;
    }

    public function getUsuarioExclusao()
    {
        return $this->usuarioExclusao;
    }

    public function setUsuarioCadastro(Usuario $usuarioCadastro)
    {
        $this->usuarioCadastro = $usuarioCadastro;
        return $this;
    }

    public function setUsuarioExclusao(Usuario $usuarioExclusao)
    {
        $this->usuarioExclusao = $usuarioExclusao;
        return $this;
    }

    public function getSexo()
    {
        return $this->sexo;
    }

    public function setSexo($sexo)
    {
        if (!in_array($sexo, array(\DesportoBundle\Doctrine\Type\EnumSexoType::MASCULINO, \DesportoBundle\Doctrine\Type\EnumSexoType::FEMININO))) {
            throw new InvalidArgumentException("Sexo Inválida");
        }
        
        $this->sexo = $sexo;
        return $this;
    }


    public function getInscricoes()
    {
        return $this->inscricoes;
    }

    public function setInscricoes(Collection $campeonatosEquipes)
    {
        $this->inscricoes = $campeonatosEquipes;
        return $this;
    }

    
    public function getPublicFoto()
    {
        if (!empty($this->foto)) {
            return $this->foto;
        } else {
            if ($this->sexo == \DesportoBundle\Doctrine\Type\EnumSexoType::MASCULINO) {
                return "user-man.jpg";
            } elseif ($this->sexo == \DesportoBundle\Doctrine\Type\EnumSexoType::FEMININO) {
                return "user-woman.jpg";
            }
        }
    }
    
    /**
     * 
     * @return ArrayCollection
     */
    public function getGols()
    {
        $gols = new ArrayCollection();
        foreach ($this->inscricoes as $inscricao) {
            foreach ($inscricao->getGols() as $gol) {
                $gols->add($gol);
            }
        }
        return $gols;
    }
    
    /**
     * 
     * @return ArrayCollection
     */
    public function getSuspensoes()
    {
        $suspensoes = new ArrayCollection();
        foreach ($this->inscricoes as $inscricao) {
            /* @var $inscricao InscricaoProfissional */
            foreach ($inscricao->getSuspensoes() as $suspensao) {
                $suspensoes->add($suspensao);
            }
        }
        return $suspensoes;
    }

    /**
     * 
     * @return ArrayCollection
     */
    public function getCartoesAmarelos()
    {
        $cartoesAmarelos = new ArrayCollection();
        foreach ($this->inscricoes as $inscricao) {
            foreach ($inscricao->getCartoesAmarelos() as $cartao) {
                $cartoesAmarelos->add($cartao);
            }
        }
        return $cartoesAmarelos;
    }
    
    /**
     * 
     * @return ArrayCollection
     */
    public function getCartoesVermelhos()
    {
        $cartoesVermelhos = new ArrayCollection();
        foreach ($this->inscricoes as $inscricao) {
            foreach ($inscricao->getCartoesVermelhos() as $cartao) {
                $cartoesVermelhos->add($cartao);
            }
        }
        return $cartoesVermelhos;
    }

    
}

src/DesportoBundle/Controller/ProfissionalController.php
<?php

namespace DesportoBundle\Controller;

use DesportoBundle\Entity\EdicaoCampeonato;
use DesportoBundle\Entity\Profissional;
use DesportoBundle\Form\ProfissionalType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\StreamedResponse;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/**
 * Description of ProfissionalController
 * @Route("/profissional")
 * @author Luciano
 */
class ProfissionalController extends Controller
{
    
    /**
     * @Route("/", name="profissional_index")
     * @Template()
     */
    public function indexAction() 
    {
        return array();
    }
    
    /**
     * @Route("/pagination", name="profissional_pagination")
     * @Template()
     */
    public function paginationAction(Request $request)
    {
        $firstResult    = $request->query->getInt("start");
        $maxResults     = $request->query->getInt("length");
        $busca          = $request->get("search");
        
        $repProfissional = $this->getDoctrine()
                            ->getRepository(Profissional::class);
        $profissionais = $repProfissional->getProfissionais($busca['value'], $maxResults, $firstResult);
        
        $dados = array();
        foreach ($profissionais as $profissional) {
            $dados[] = [
                $this->renderView("DesportoBundle::Profissional/pagination.html.twig", ['profissional' => $profissional]),
            ];
        }
        
        $recordsTotal = $repProfissional->count();
        if (!empty($busca['value'])) {
            $recordsFiltered = $repProfissional->count($busca['value']);
        } else {
            $recordsFiltered = $recordsTotal;
        }
        
        
        $return = [
            'draw' => $request->get("draw"),
            'recordsTotal' => $recordsTotal,
            'recordsFiltered' => $recordsFiltered,
            'data' => $dados,
        ];
        return new Response(json_encode($return));
    }

    /**
     * @Route("/editar/{id}", name="profissional_form")
     * @Template()
     * 
     * @param Request $request
     * @return RedirectResponse
     */
    public function formAction(Request $request, $id = null) 
    {
        $em = $this->getDoctrine()->getManager();
        if ($id>0) {
            $profissional = $em->find(Profissional::class, $id);
        } else {
            $profissional = new Profissional();
            $profissional->setUsuarioCadastro($this->getUser());
        }
        $arquivos = clone $profissional->getArquivos();
        $form = $this->createForm(ProfissionalType::class, $profissional);
        $form->handleRequest($request);
        if ($form->isValid()) {
            $this->get("profissional")->salvarProfissional($profissional, $arquivos);                        
            return new RedirectResponse($this->generateUrl('profissional_index'));
        }
        
        return ['form'=>$form->createView(), 'profissional'=>$profissional];
    }
    
    /**
     * @Route("/perfil/{id}", name="profissional_perfil")
     * @Template()
     */
    public function perfilAction(Profissional $profissional) 
    {
        return ['profissional'=>$profissional];
    }

    
    /**
     * @Route("/download/{nome}", name="profissional_arquivo_download")
     * 
     * @param int $nome Nome do Arquivo
     * @return Response
     */
    public function downloadArquivoAction($nome = null)
    {
        if (is_null($nome)) {
            throw new NotFoundHttpException;
        }
        if (file_exists($this->get('kernel')->getRootDir() . '/../web/uploads/arquivos/'.$nome)) {
            return $this->get("upload")->download($this->get('kernel')->getRootDir() . '/../web/uploads/arquivos/'.$nome);
        } elseif (file_exists($this->get('kernel')->getRootDir() . '/../web/uploads/temp/'.$nome)) {
            return $this->get("upload")->download($this->get('kernel')->getRootDir() . '/../web/uploads/temp/'.$nome);
        } else {
            throw new NotFoundHttpException;
        }
    }
    
    /**
     * @Route("/find/jogadores/disponiveis/{campeonato}", name="profissional_find_jogadores_disponiveis")
     * @param Request $request
     */
    public function findJogadoresAction(EdicaoCampeonato $campeonato, Request $request)
    {
        $equipe = $request->get("equipe");
        $strBusca = $request->get("busca");
        $inscritos = $request->get('inscritos');
        
        $profissionais = $this->getDoctrine()
                ->getRepository(Profissional::class)
                ->getJogadoresDisponíveis($campeonato, $equipe, $strBusca, $inscritos);

        return new Response(json_encode($this->preparaResultFindProfissionais($profissionais)));
    }
    
    /**
     * @Route("/find/diretores/disponiveis/{campeonato}", name="profissional_find_diretores_disponiveis")
     * @param Request $request
     */
    public function findDiretoresDisponiveisAction(EdicaoCampeonato $campeonato, Request $request)
    {
        $equipe = $request->get("equipe");
        $strBusca = $request->get("busca");
        
        $profissionais = $this->getDoctrine()
                ->getRepository(Profissional::class)
                ->getDiretoresDisponíveis($campeonato, $equipe, $strBusca);

        return new Response(json_encode($this->preparaResultFindProfissionais($profissionais)));
    }
    
    /**
     * @Route("/find/treinadores/disponiveis/{campeonato}", name="profissional_find_treinadores_disponiveis")
     * @param Request $request
     */
    public function findTreinadoresDisponíveisAction(EdicaoCampeonato $campeonato, Request $request)
    {
        $equipe = $request->get("equipe");
        $strBusca = $request->get("busca");
        
        $profissionais = $this->getDoctrine()
                ->getRepository(Profissional::class)
                ->getTreinadoresDisponíveis($campeonato, $equipe, $strBusca);

        return new Response(json_encode($this->preparaResultFindProfissionais($profissionais)));
    }
    
    
    private function preparaResultFindProfissionais($profissionais)
    {
        $items = array();
        foreach ($profissionais as $profissional) {
            /* @var $profissional Profissional */
            $items[] = [
                'id' => $profissional->getId(),
                'nome' => $profissional->getNome(),
                'cpf' => $this->get("string_filters")->cpf($profissional->getCpf())
            ];
        }

        $return['total_count'] = count($profissionais);
        $return['items'] = $items;
        $return['incomplete_results'] = false;

        return $return;
    }
    
    /**
     * @Route("/exportar", name="profissional_exportar")
     * @param Request $request
     * @return StreamedResponse
     */
    public function exportarAction(Request $request)
    {        
        $response = new StreamedResponse();
        $response->setCallback(function() use ($request) {
            $handle = fopen('php://output', 'w+');

            // Add the header of the CSV file
            fputcsv($handle, array('Nome', 'CPF', 'Telefone', 'Endereço', 'Sexo', 'Nascimento'),';');
            
            $profissionais = $this->getDoctrine()->getRepository(Profissional::class)->findBy(['id' => array_values($request->get("profissionais"))]);
            
            foreach ($profissionais as $profissional) {
                fputcsv(
                    $handle, 
                    array($profissional->getNome(), $this->get('string_filters')->cpf($profissional->getCpf()), $this->get('string_filters')->telefone($profissional->getTelefone()), $profissional->getEndereco(), $profissional->getSexo(), $profissional->getNascimento()->format("d/m/Y")),
                    ';' 
                );                
            }

            fclose($handle);
        });

        $response->setStatusCode(200);
        $response->headers->set('Content-Type', 'text/csv; charset=utf-8');
        $response->headers->set('Content-Disposition', 'attachment; filename="profissionais.csv"');
        
        return $response;
    }

    /**
     * @Route("/excluir", name="profissional_excluir")
     * @param Request $request
     * @return RedirectResponse
     */
    public function excluirAction(Request $request)
    {
        $profissionais = $this->getDoctrine()->getRepository(Profissional::class)->findBy(['id' => array_values($request->get("profissionais"))]);

        $dataExclusao = new \DateTime("now"); 
        foreach ($profissionais as $profissional) {
             /* @var $profissional Profissional */
             $profissional->setDataExclusao($dataExclusao);
             $profissional->setUsuarioExclusao($this->getUser());
             $this->getDoctrine()->getManager()->persist($profissional);
         }
         $this->getDoctrine()->getManager()->flush();
         
         return new RedirectResponse($this->generateUrl('profissional_index'));
    }

    
}

src/DesportoBundle/Resources/views/Profissional/form.html.twig
{% extends "DesportoBundle::layout.html.twig" %}
{% form_theme form 'DesportoBundle:Form:fields.html.twig' %}
{% block title %}Desporto | Cadastro de Profissional{% endblock %}
{% block head %}
    <link href="{{ asset('bundles/desporto/css/dropzone.css') }}" rel="stylesheet" />
    <script src="{{ asset('bundles/desporto/js/jquery.validate.min.js') }}"></script>
    <script src="{{ asset('bundles/desporto/js/messages_ptbr.js') }}"></script>
    <script src="{{ asset('bundles/desporto/js/validate/additional-methods.js') }}"></script>
    <script src="{{ asset('bundles/desporto/js/jquery.maskedinput.min.js') }}"></script>
    <script src="{{ asset('bundles/desporto/js/jquery.maskMoney.js') }}"></script>
    <script src="{{ asset('bundles/desporto/js/jquery-ui-1.10.3.min.js') }}"></script>
    <script src="{{ asset('bundles/desporto/js/dropzone.min.js') }}"></script>
    <script src="{{ asset('bundles/desporto/js/bootbox.min.js') }}"></script>
    {% include 'DesportoBundle::Profissional/cadastro.js.twig' %}
{% endblock %}

{% block mainpanel %}
<div class="pageheader">
    <div class="media">
        <div class="pageicon pull-left">
            <i class="fa fa-pencil"></i>
        </div>
        <div class="media-body">
            <ul class="breadcrumb">
                <li><a href="{{ path('index') }}"><i class="glyphicon glyphicon-home"></i></a></li>
                <li><a href="{{ path('profissional_index') }}">Profissional</a></li>
                <li>{{ profissional.getid>0 ? "Edição de" : "Cadastro de" }} Profissional </li>
            </ul>
            <h4>{{ profissional.getid>0 ? "Edição de" : "Cadastro de" }} Profissional </h4>
        </div>
    </div><!-- media -->
</div><!-- pageheader -->

<div class="contentpanel">
    <div class="row">
        <div class="col-md-12">
            <form method="POST" class="form-horizontal form-bordered" id="basicForm" action="">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h5 class="panel-title">Dados pessoais</h5>
                        <p>
                            Compos com * são obrigatórios
                        </p>
                    </div>
                    <div class="panel-body">
                        {{ form_errors(form) }}
                        <div class="row">
                            {{ form_row(form.nome) }}
                            {{ form_row(form.nascimento) }}
                            {{ form_row(form.sexo) }}
                            {{ form_row(form.cpf) }}
                            {{ form_row(form.rg) }}
                            {{ form_row(form.endereco) }}
                            {{ form_row(form.telefone) }}
                        </div><!-- row -->
                    </div><!-- panel-body -->
                </div><!-- panel -->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h5 class="panel-title">Foto</h5>
                    </div>
                    <div class="panel-body">
                        <div class="media-options foto">
                            <button type="button" class="btn btn-success fotoinput-button">Adicionar Foto</button>
                        </div>
                        {{ form_widget(form.foto) }}
                        
                        <div  class="row media-manager">
                            <div id="previews-foto">
                                {% include 'DesportoBundle::Form/upload-template.html.twig' %}
                            </div>
                        </div>
                    </div>
                </div><!-- panel -->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h5 class="panel-title">Documentos</h5>
                    </div>
                    <div class="panel-body">
                        <div class="media-options arquivos">
                            <button type="button" class="btn btn-success fileinput-button">Adicionar Arquivos</button>
                        </div>
                        <hr/>
                        <div  class="row media-manager">
                            <div id="previews-arquivos">
                            </div>
                        </div>
                    </div>
                </div><!-- panel -->


                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="row">
                            <button class="btn btn-primary mr5">Salvar</button>
                            <img src="{{ asset('bundles/desporto/images/loading.gif') }}" id="loading" alt="Carregando" />
                            <a class="btn btn-default" href="javascript:history.back();">Voltar</a>
                        </div>
                    </div>
                </div><!-- panel -->
                
                {{ form_row(form._token) }}
            </form>
            
        </div><!-- col-md-12 -->
    </div><!-- row -->
</div><!-- contentpanel -->
{% endblock %}

src/DesportoBundle/Resources/views/Profissional/pagination.html.twig
<div>
    <div class="ckbox ckbox-default pull-left">
        <input id="profissionalcheck{{ profissional.id }}" type="checkbox" name="profissionais[]" value="{{ profissional.id }}">
        <label for="profissionalcheck{{ profissional.id }}"></label>
    </div>

    <div class="media">
        <div class="pull-right">
            <div class="btn-group" role="group" aria-label="...">
                <a  href="{{ path('profissional_form', {id: profissional.id}) }}" class="btn btn-white btn-xs tooltips" title="Editar"><i class="fa fa-pencil"></i></a>
                <a  href="{{ path('profissional_perfil', {id: profissional.id}) }}" class="btn btn-white btn-xs tooltips" title="Perfil"><i class="fa fa-search"></i></a>
            </div>
        </div>

        <div class="pull-left">
            <img class="img-circle" src="{{ path('profissional_arquivo_download', {nome: profissional.publicFoto}) }}" alt="...">
        </div>
        <div class="media-body">
            <h4 class="media-heading">{{ profissional.nome }} <small>{{ profissional.cpf|cpf }}</small></h4>
            <div class="media-content">
                <i class="fa fa-calendar"></i> {{ profissional.nascimento.format('d/m/Y') }}
                <ul class="list-unstyled">
                    <li><i class="fa fa-phone"></i> {{ profissional.telefone|telefone }}</li>
                    <li><i class="fa fa-map-marker"></i> {{ profissional.endereco }}</li>
                </ul>
            </div>
        </div>
    </div><!-- media -->
</div><!-- list-group -->   

src/DesportoBundle/Resources/views/Profissional/perfil.html.twig
{% extends "DesportoBundle::layout.html.twig" %}
{% block title %}Desporto | Perfil do Profissional{% endblock %}
{% block head %}
{% endblock %}

{% block mainpanel %}
    <div class="pageheader">
        <div class="media">
            <div class="pageicon pull-left">
                <i class="fa fa-user"></i>
            </div>
            <div class="media-body">
                <ul class="breadcrumb">
                    <li><a href="{{ path('index') }}"><i class="glyphicon glyphicon-home"></i></a></li>
                    <li><a href="{{ path('profissional_index') }}">Profissional</a></li>
                    <li>Perfil do Profissional </li>
                </ul>
                <h4>Perfil do Profissional </h4>
            </div>
        </div><!-- media -->
    </div><!-- pageheader -->

    <div class="contentpanel">

        <div class="row">
            <div class="col-sm-12 col-md-3">
                <div class="text-center">
                    <img src="{{ path('profissional_arquivo_download', {nome: profissional.publicFoto}) }}" class="img-circle img-offline img-responsive img-profile" alt="" />
                    <h4 class="profile-name mb5">{{ profissional.nome }}</h4>
                    <div><i class="fa fa-map-marker"></i> {{ profissional.endereco }}</div>
                    <div><i class="fa fa-calendar"></i> {{ profissional.nascimento.format("d/m/Y") }} </div>
                    <div><i class="fa fa-phone"></i> {{ profissional.telefone|telefone }} </div>
                </div><!-- text-center -->
            </div><!-- col-sm-4 col-md-3 -->
            <div class="col-sm-12 col-md-9">
                <div class="row">
                    <div class="col-sm-3">
                        <h4>Gols</h4>
                    </div>
                    <div class="col-sm-9">
                        <h4>{{ profissional.gols.count }}</h4>
                    </div>
                </div>
                <hr/>
                <div class="row">
                    <div class="col-sm-3">
                        <h4>Cartões Amarelos</h4>
                    </div>
                    <div class="col-sm-9">
                        <h4>{{ profissional.cartoesAmarelos.count }}</h4>
                    </div>
                </div>
                <hr/>
                <div class="row">
                    <div class="col-sm-3">
                        <h4>Cartões Vermelhos</h4>
                    </div>
                    <div class="col-sm-9">
                        <h4>{{ profissional.cartoesvermelhos.count }}</h4>
                    </div>
                </div>
                <hr/>
                <div class="row">
                    <div class="col-sm-3">
                        <h4>Suspensões</h4>
                    </div>
                    <div class="col-sm-9">
                        <h4>{{ profissional.suspensoes.count }}</h4>
                    </div>
                </div>
                <hr/>
            </div>
        </div>
        <hr/>
        <div class="row">
            <div class="col-sm-12   ">
                <table class="table table-hover table-lg">
                    <thead>
                        <tr>
                            <th> Campeonato</th>
                            <th> Equipe </th>
                            <th class="text-center"> Gols </th>
                            <th class="tooltips text-center" title="Cartões Amarelos"> CA </th>
                            <th class="tooltips text-center" title="Cartões Vermelhos"> CV </th>
                            <th class="tooltips text-center" title="Suspensões"> S </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for inscricao in profissional.inscricoes %}
                        <tr>
                            <td> {{ inscricao.edicaoCampeonato.campeonato.nome }} - {{ inscricao.edicaoCampeonato.edicao }} </td>
                            <td> {{ inscricao.equipe.nome }} </td>
                            <td class="text-center"> {{ inscricao.gols.count }} </td>
                            <td class="tooltips text-center" title="Cartões Amarelos"> {{ inscricao.cartoesAmarelos.count }} </td>
                            <td class="tooltips  text-center" title="Cartões Varmelhos" > {{ inscricao.cartoesVermelhos.count }} </td>
                            <td class="tooltips  text-center" title="Suspensões" > {{ inscricao.suspensoes.count }} </td>
                        </tr>
                        {% else %}
                            <tr>
                                <td colspan="5"> Ainda não disputou nenhum campeonato. </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                    
                </table>
            </div>
        </div>



    </div><!-- contentpanel -->
{% endblock %}